sudo: false

language: python

python:
  - 3.6

# install dependencies
install:
  - pip install -r requirements.txt
  - pip install codecov
  - pip install flake8

script:
  - coverage erase
  - coverage run --source ad_server -m pytest && coverage html
  - flake8 . --exit-zero

after_success:
  - codecov
