"""empty message

Revision ID: 6e5829dd9b62
Revises: d3cc4aaac5df
Create Date: 2019-12-29 19:35:32.819558

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e5829dd9b62'
down_revision = 'd3cc4aaac5df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('album_genre', sa.Column('genre_id', sa.Integer(), nullable=False))
    op.drop_constraint('album_genre_artist_id_fkey', 'album_genre', type_='foreignkey')
    op.create_foreign_key(None, 'album_genre', 'genre', ['genre_id'], ['id'])
    op.drop_column('album_genre', 'artist_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('album_genre', sa.Column('artist_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'album_genre', type_='foreignkey')
    op.create_foreign_key('album_genre_artist_id_fkey', 'album_genre', 'artist', ['artist_id'], ['id'])
    op.drop_column('album_genre', 'genre_id')
    # ### end Alembic commands ###
