"""empty message

Revision ID: 7429d551795a
Revises: cd5d8af90164
Create Date: 2019-12-29 18:00:36.558333

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7429d551795a'
down_revision = 'cd5d8af90164'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'genre', ['id'])
    op.drop_column('genre', 'test')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('genre', sa.Column('test', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'genre', type_='unique')
    # ### end Alembic commands ###
