"""empty message

Revision ID: c7afcb56fe29
Revises: 6e5829dd9b62
Create Date: 2019-12-31 02:14:00.667071

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7afcb56fe29'
down_revision = '6e5829dd9b62'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'genre', ['title'])
    op.add_column('song', sa.Column('filepath', sa.String(length=128), nullable=False))
    op.alter_column('song', 'album_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('song', 'file_path')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('song', sa.Column('file_path', sa.VARCHAR(length=128), autoincrement=False, nullable=False))
    op.alter_column('song', 'album_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('song', 'filepath')
    op.drop_constraint(None, 'genre', type_='unique')
    # ### end Alembic commands ###
