"""New design

Revision ID: d3cc4aaac5df
Revises: 7429d551795a
Create Date: 2019-12-29 19:21:00.124607

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3cc4aaac5df'
down_revision = '7429d551795a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('album_genre',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('album_id', sa.Integer(), nullable=False),
    sa.Column('artist_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['album_id'], ['album.id'], ),
    sa.ForeignKeyConstraint(['artist_id'], ['artist.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('album_artist', 'album_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('album_artist', 'artist_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint('song_genre_id_fkey', 'song', type_='foreignkey')
    op.drop_column('song', 'genre_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('song', sa.Column('genre_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('song_genre_id_fkey', 'song', 'genre', ['genre_id'], ['id'])
    op.alter_column('album_artist', 'artist_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('album_artist', 'album_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_table('album_genre')
    # ### end Alembic commands ###
